// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3NNJFNFCblV9gHXF8QMaWYsgeUtuf5ro',
    appId: '1:918905996030:web:4295e3c930df8e41e39baf',
    messagingSenderId: '918905996030',
    projectId: 'auth1-6f99a',
    authDomain: 'auth1-6f99a.firebaseapp.com',
    storageBucket: 'auth1-6f99a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLG7Gh8QJlNm_WZHy16XDfN7MV7zfwRes',
    appId: '1:918905996030:android:5c681362fd0ca7ece39baf',
    messagingSenderId: '918905996030',
    projectId: 'auth1-6f99a',
    storageBucket: 'auth1-6f99a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbM09NOAutN-aPbFML0HJu0ztvuTy1eHM',
    appId: '1:918905996030:ios:1a95269bd69c4df6e39baf',
    messagingSenderId: '918905996030',
    projectId: 'auth1-6f99a',
    storageBucket: 'auth1-6f99a.appspot.com',
    iosBundleId: 'com.example.sns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbM09NOAutN-aPbFML0HJu0ztvuTy1eHM',
    appId: '1:918905996030:ios:8e7ea6f4c338319fe39baf',
    messagingSenderId: '918905996030',
    projectId: 'auth1-6f99a',
    storageBucket: 'auth1-6f99a.appspot.com',
    iosBundleId: 'com.example.sns.RunnerTests',
  );
}
